---
apiVersion: api.clever-cloud.com/v1
kind: Azimutt
metadata:
  namespace: default
  name: azimutt
spec:
  organisation: orga_<uuid v4>
  instance:
    region: par
    plan: free
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-azimutt
  name: debian-azimutt
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-azimutt
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-azimutt
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-azimutt
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-azimutt
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-azimutt
  labels:
    app: debian-azimutt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-azimutt
  template:
    metadata:
      labels:
        app: debian-azimutt
    spec:
      serviceAccountName: debian-azimutt
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-azimutt
          command:
            - "sleep"
            - "3600"
          env: []
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
